### PR TITLE
Updated Spatial Persistence checkouts

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Updated Spatial Persistence checkouts

### CODE REVIEW

**Review by StephenHodgson — CHANGES_REQUESTED** [review]
@SimonDarksideJ please be sure to update the dependencies in the XRTK/SpatialPersistence.ASA package.json

**Comment by SimonDarksideJ** [comment]
Can you give me a clue where to find the Preview Number version then for the updated Spatial Persistence package?  Still shows as 0.3 in dev @StephenHodgson

**Comment by StephenHodgson** [comment]
package.json

**Comment by SimonDarksideJ** [comment]
Except the version shown for the spatial persistence service system at present is 0.3.0 (no preview)
https://github.com/XRTK/com.xrtk.spatial-persistence/blob/development/XRTK.SpatialPersistence/Packages/com.xrtk.spatial-persistence/package.json

**Comment by StephenHodgson** [comment]
https://github.com/XRTK/com.xrtk.spatial-persistence.asa/blob/ca8d2b0c73a7a0995dd8366f38d086e4e9f510a1/XRTK.SpatialPersistence.ASA/Packages/com.xrtk.spatial-persistence.asa/package.json#L25

**Comment by SimonDarksideJ** [comment]
Closing as these already seem to be up to date

**Pull request closed without merging**
